### ISSUE TITLE
Unable install to bootstrap 

### ISSUE THREAD

**Issue by DHANAVATHgANESH** [termux/termux-boot#243] opened 2024-11-26 15:59 UTC
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:
![Screenshot_20241126_212110_Termux](https://github.com/user-attachments/assets/aea8d600-3c9f-4ddc-8f17-11958b800b3a)
![Uploading Screenshot_20241126_212110_Termux.jpg…]()

**Comment by twaik** [comment] 2024-11-26 16:01
Duplicate of https://github.com/termux/termux-boot/issues/241
Stop it please.

**Closed** 2024-11-26 16:02 UTC
